feature: Compose Multiplatform 1.6.10-beta01 Lifecycle and Navigation libraries
JetBrains/kotlin-multiplatform-dev-docs pull request #103
Opened 2024-04-15 16:36 UTC by zamulla

Added pages detailing experimental libraries for Lifecycle and Navigation in the 1.6.10-beta01 release.

2024-04-15 16:57 UTC, MatkovIvan commented on topics/compose/compose-lifecycle.md
> +with the `Lifecycle` class to observe activity states.
Android only statement in "Multiplatform" section

2024-04-15 16:57 UTC, MatkovIvan commented on topics/compose/compose-lifecycle.md
> +| viewDidDisappear          | ON_STOP         | STARTED → CREATED      |
Put all code names in `
```suggestion
| `viewDidDisappear`          | `ON_STOP`         | `STARTED` → `CREATED`      |
```

2024-04-17 12:46 UTC, danil-pavlov requested changes

2024-04-17 12:46 UTC, danil-pavlov commented on topics/compose/compose-navigation-routing.md
> +Things to note:
Feels a little abrupt, some alternatives for the intro phrase: "Also, keep in mind that: ", "It's also important to note that:", "Also, consider the following implementation aspects:"

2024-04-17 12:46 UTC, danil-pavlov commented on topics/compose/compose-lifecycle.md
> +* skip the `CREATED` state as the application is always attached to the page,
```suggestion
* Skip the `CREATED` state, as the application is always attached to the page.
```

2024-04-17 14:16 UTC, zamulla commented on topics/compose/compose-lifecycle.md
> +Lifecycle functionality on Android originally consisted of [a set of callbacks](https://developer.android.com/guide/components/activities/activity-lifecycle).
I just like history. Makes sense, squished all of that down.

2024-04-17 14:24 UTC, merged