feature: Compose 1.6.10 multimodule resources
JetBrains/kotlin-multiplatform-dev-docs pull request #104
Opened 2024-04-17 15:40 UTC by zamulla

2024-04-26 17:31 UTC, danil-pavlov requested changes

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +> Available starting with Compose Multiplatform %composeEapVersion%-beta01.
```suggestion
> Accessing resources from external libraries is available starting with Compose Multiplatform %composeEapVersion%-beta01.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +of the same thing (1 _book_, many _books_ and so on) without creating programmatically unrelated strings.
```suggestion
of the same thing (1 _book_, many _books_, and so on) without creating programmatically unrelated strings.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +The concept and base implementation in Compose Multiplatform is the same as for [quantity strings](https://developer.android.com/guide/topics/resources/string-resource#Plurals)
```suggestion
The concept and base implementation in Compose Multiplatform are the same as for quantity strings
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +on Android (follow the link to read more about nuances and best practices of using plurals in your project).
```suggestion
on Android. See the [Android documentation](https://developer.android.com/guide/topics/resources/string-resource#Plurals) for more about nuances and best practices of using plurals in your project.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +To define a plural, add a `<plurals>` element to any .xml file in your `composeResources/values` directory.
```suggestion
To define a plural, add a `<plurals>` element to any XML file in your `composeResources/values` directory.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +To enable this functionality, your project needs to use Kotlin 2.0.0-Beta5 or newer and Gradle 7.6 or newer.
```suggestion
For this functionality, your project needs to use Kotlin 2.0.0-Beta5 or newer and Gradle 7.6 or newer.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +> Available starting with Compose Multiplatform %composeEapVersion%-beta01.
```suggestion
> Plurals are available starting with Compose Multiplatform %composeEapVersion%-beta01.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +> Since the version %composeEapVersion%-beta01, limitations on resource placement have been lifted:
```suggestion
> Since %composeEapVersion%-beta01, limitations on resource placement have been lifted:
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +  considered for every language: for example, `zero` is ignored for English, because it is the same as any other plural
```suggestion
  considered for every language: for example, `zero` is ignored for English because it is the same as any other plural
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +As such, you can combine `plurals` resources with other simple resources in the one XML file, under one `<resources>` element:
```suggestion
As such, you can combine `plurals` resources with other simple resources in one XML file under one `<resources>` element:
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +> Starting with Compose Multiplatform %composeEapVersion%-beta01, string arrays are a separate resource type.
```suggestion
> Starting with Compose Multiplatform %composeEapVersion%-beta01, [string arrays](#string-arrays) are a separate resource type.
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +   * `packageOfResClass` allows you to assign the generated `Res` class to a particular package (for access within the code
```suggestion
   * `packageOfResClass` allows you to assign the generated `Res` class to a particular package (for access within the code,
```

2024-04-26 17:31 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +     as well as for isolation in a final artifact.) By default, Compose Multiplatform uses the
```suggestion
     as well as for isolation in a final artifact). By default, Compose Multiplatform uses the
```

2024-05-08 10:49 UTC, zamulla commented
The EAP doc for multiplatform resources was published behind a version switch (to avoid the amount of notes and warnings that is needed to keep the EAP and stable information on the same page): https://www.jetbrains.com/help/kotlin-multiplatform-dev/1.6.10/compose-images-resources.html

I took into account all comments that remained relevant.

2024-05-08 10:49 UTC, closed without merging