feat: move the scrollbars tutorial from github
JetBrains/kotlin-multiplatform-dev-docs pull request #106
Opened 2024-04-19 01:19 UTC by ElviraMustafina

Moved the first desktop tutorial from GitHub to the Desktop-specific components section: minor changes to code samples and text, new gifs.

2024-04-25 09:36 UTC, igordmn approved these changes

2024-04-26 18:12 UTC, danil-pavlov requested changes

2024-04-29 17:18 UTC, ElviraMustafina commented on mpd.tree
> +        <toc-element id="compose-desktop-components.md" toc-title="Desktop-specific components">
This topic is the list of tutorials intros with links to GitHub. It will be just a title in the tree when all tutorials have their own topics. So, it's a temporary UX issue.

2024-08-31 00:41 UTC, ElviraMustafina commented on mpd.tree
> +        <toc-element id="compose-desktop-components.md" toc-title="Desktop-specific components">
We can temporarily place new topics on the same level (inside "Compose Multiplatform UI framework"), and then move them under "Desktop-specific components" when everything is ready. WDYT?

2024-09-03 12:16 UTC, danil-pavlov commented on mpd.tree
> +        <toc-element id="compose-desktop-components.md" toc-title="Desktop-specific components">
Yes, that works too, let's keep them on the same level until we have enough pages to make a section

For a transitional period, when you've already moved some pages to make a separate section, but not all of them, you can use the following structure:

```
Desktop-specific components - empty
   └── Overview with the list of remaining tutorials with links to GitHub
   ├── Scrollbars
   ├── ...
```

2024-09-10 12:14 UTC, zamulla requested changes
A couple more things to consider.

2024-09-10 12:14 UTC, zamulla commented on topics/compose/compose-desktop-scrollbars.md
> +Lazy components are much more efficient since they only compose the items as they're needed.
I'd qualify this statement with something like "...much more efficient _when you expect a lot of items in the list_". Otherwise it's just dissing perfectly good Columns for no reason :)

2024-09-10 16:18 UTC, zamulla approved these changes
Looks good 👍

2024-09-10 16:35 UTC, merged