update: Kotlin Compose compiler
JetBrains/kotlin-multiplatform-dev-docs pull request #112
Opened 2024-04-24 10:48 UTC by zamulla

2024-04-24 16:27 UTC, nickbutcher commented on topics/compose/compose-compiler.md
> +When applied together with the Android Gradle plugin, the Kotlin Compose plugin will override the coordinates of the
```suggestion
When applied together with the Android Gradle plugin, the Kotlin Compose Compiler plugin will override the coordinates of the
```

2024-04-25 10:09 UTC, nickbutcher commented on topics/compose/compose-compatibility-and-versioning.md
> +> [The Kotlin Compose compiler](compose-compiler.md) will be supported in the 1.6.10 Compose Multiplatform release.
```suggestion
> [The Compose compiler](compose-compiler.md) will be supported in the 1.6.10 Compose Multiplatform release.
```

2024-04-25 13:06 UTC, ShikaSD commented on topics/compose/compose-compiler.md
> +### metricsDestination
Can you update the docs according to https://github.com/JetBrains/kotlin/commit/016300e17c6cb2ecfe67c7a180a1e30057d15da5? 

Seems like the original javadoc had the same comment for both metrics and reports destination parameters.

2024-04-26 16:51 UTC, danil-pavlov requested changes

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +To try Compose compiler 2.0.0 with the stable version of Compose Multiplatform (1.6.2 or older), use this configuration:
Maybe a subheader for this part? like "Test Compose compiler" to highlight and distinguish from the previous setup

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +5. If you are using compiler options for the Jetpack Compose compiler, they should now be set in the `composeCompiler{}` block.
```suggestion
5. If you are using compiler options for the Jetpack Compose compiler, set them in the `composeCompiler {}` block.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +You can use it to configure the compiler in the `composeCompiler{}` block of the `build.gradle.kts` file for the module
```suggestion
You can use it to configure the compiler in the `composeCompiler {}` block of the `build.gradle.kts` file for the module
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +4. If you are using compiler options for the Jetpack Compose compiler, they should now be set in the `composeCompiler{}` block.
```suggestion
4. If you are using compiler options for the Jetpack Compose compiler, set them in the `composeCompiler {}` block.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +To enable only one specific Kotlin platform (for example, Kotlin/JVM):
```suggestion
To enable only one specific Kotlin platform, for example, Kotlin/JVM:
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +To disable the plugin for one or more Kotlin platforms (for example, Kotlin/Native and Kotlin/JS):
```suggestion
To disable the plugin for one or more Kotlin platforms, for example, Kotlin/Native and Kotlin/JS:
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +If `true`, enable strong skipping mode.
```suggestion
If `true`, enable Strong Skipping mode.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +For details, see the [description for Strong Skipping Mode](https://github.com/androidx/androidx/blob/androidx-main/compose/compiler/design/strong-skipping.md)
```suggestion
For details, see the [description of Strong Skipping mode](https://github.com/androidx/androidx/blob/androidx-main/compose/compiler/design/strong-skipping.md)
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +> The Compose compiler is merged into the Kotlin repository as of Kotlin version 2.0.0-RC2.
```suggestion
> The Compose compiler has been merged into the Kotlin repository since Kotlin 2.0.0-RC2.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +When applied together with the Android Gradle plugin, this Compose compiler plugin will override the coordinates
```suggestion
When applied with the Android Gradle plugin (AGP), this Compose compiler plugin will override the coordinates
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +to be released soon after Kotlin 2.0.0-RC2.
```suggestion
which will be released soon after Kotlin 2.0.0-RC2.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +The Compose compiler Gradle plugin offers an options DSL.
```suggestion
The Compose compiler Gradle plugin offers DSL with different options.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +4. If you use the Android build feature in your Gradle configuration (`android.buildFeatures.compose = true`),
```suggestion
4. If you use the Android build feature in your Gradle configuration (`android.buildFeatures.compose = true`)
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +the metrics show which of your composable functions are skippable, which are restartable, which are readonly, etc.
```suggestion
the metrics show which composable functions are skippable, restartable, read-only, and so on.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +the reports show which of your composable functions are skippable, which are restartable, which are readonly, etc.
```suggestion
the reports show which composable functions are skippable, restartable, read-only, and so on.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +This results in fewer slots being used and fewer comparisons being done at runtime.
```suggestion
This results in fewer slots being used and fewer comparisons being made at runtime.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +Intrinsic remember is an optimization mode which inlines `remember` invocations and replaces `.equals` comparison for keys
```suggestion
Intrinsic remember is an optimization mode which inlines `remember` invocations and replaces `.equals` comparisons for keys
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +This feature is considered experimental and is thus disabled by default.
```suggestion
This feature is considered [Experimental](supported-platforms.md#core-kotlin-multiplatform-technology-stability-levels) and is thus disabled by default.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +Strong Skipping is an experimental mode that improves the runtime performance of your application by skipping unnecessary
```suggestion
Strong Skipping is an [Experimental](supported-platforms.md#core-kotlin-multiplatform-technology-stability-levels) mode that improves the runtime performance of your application by skipping unnecessary
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +This is an experimental optimization that improves the runtime performance of your application by skipping
```suggestion
This optimization improves the runtime performance of your application by skipping
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +This is an experimental optimization that improves the runtime performance of your application by skipping
Experimental status is mentioned below as well

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +This feature is considered experimental and is thus disabled by default.
could be a warning

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +For example, composables with unstable parameters become skippable and lambdas with unstable captures will be memoized.
```suggestion
For example, composables with unstable parameters become skippable, and lambdas with unstable captures are memoized.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +in Jetpack Compose documentation.
```suggestion
in the Jetpack Compose documentation.
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +Compose compiler can inject additional tracing information into the bytecode, which allows showing composable functions
```suggestion
The Compose compiler can inject additional tracing information into the bytecode, which allows it to show composable functions
```

2024-04-26 16:51 UTC, danil-pavlov commented on topics/compose/compose-compiler.md
> +To try Compose compiler 2.0.0 with the stable version of Compose Multiplatform (1.6.2 or older), use this configuration:
```suggestion
To try the Compose compiler 2.0.0 with the stable version of Compose Multiplatform (1.6.2 or older), use this configuration:
```

2024-04-29 10:11 UTC, zamulla commented on topics/compose/compose-compiler.md
> +Type: `Property<Boolean>`
Made it separate paragraphs with bold for "Type" and "Default". There are entries without a default value, this way it's more consistent.

2024-04-29 11:11 UTC, danil-pavlov approved these changes

2024-04-29 13:55 UTC, merged