feat: Compose for web in alpha
JetBrains/kotlin-multiplatform-dev-docs pull request #121
Opened 2024-05-06 10:06 UTC by AlejandraPedroza

2024-05-06 12:19 UTC, eymar reviewed
Thank you! :)

2024-05-06 12:19 UTC, eymar commented on images/compose-create-first/multiplatform-web-wizard.png
I think we'll need to update this screenshot once again after the wizard is updated itself.

Currently "Web" has "Experimental" label. But it will become "Alpha" in 1.6.10
Maybe this screenshot can be already updated by modifying the label in html of the wizard page locally.

2024-05-06 13:47 UTC, AlejandraPedroza commented on images/compose-create-first/multiplatform-web-wizard.png
I changed it locally, please check.

2024-05-06 13:52 UTC, AlejandraPedroza commented on images/compose-create-first/modules-structure.png
I think I fixed it, I don't know why it wasn't showing correctly.

2024-05-06 14:17 UTC, eymar commented on images/compose-create-first/modules-structure.png
Yes, now the page displays a new image!

2024-05-10 15:22 UTC, zamulla requested changes
Thanks! Left several suggestions to consider.

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +* In the second variant, `composeApplication` is the ID of the container added in your `index.html` file, where the UI is rendered.
I'd rephrase the second variant to make the difference clearer: in the first variant, the web app is inserted into X, in the second, the web app is inserted into Y. Maybe "rendered" is more precise, but the sentence structure should be the same for both.

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +  The `viewportContainer` parameter uses the entire body of the HTML document as the container for rendering the UI.
I don't know if I would say that a parameter uses something: parameters store things, and it's the job of functions and classes to do things. So it's the `ComposeViewport()` function using the HTML body in this case.

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-setup.md
> +                <li><strong>Chrome and Chromium-based:</strong> works by default from version 119 and subsequent versions.</li>
```suggestion
                <li><strong>Chrome and Chromium-based:</strong> works by default starting from version 119.</li>
```

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-setup.md
> +                <li><strong>Firefox:</strong> works by default from version 120 and subsequent versions.</li>
```suggestion
                <li><strong>Firefox:</strong> works by default starting from version 120.</li>
```

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-setup.md
> +                <li><strong>Safari/WebKit:</strong> Wasm GC support is currently under <a href="https://bugs.webkit.org/show_bug.cgi?id=247394">active development.</a></li>
```suggestion
                <li><strong>Safari/WebKit:</strong> Wasm GC support is currently under <a href="https://bugs.webkit.org/show_bug.cgi?id=247394">active development</a>.</li>
```

2024-05-10 15:22 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-setup.md
> +      Make sure that your browser version supports the new <a href="https://github.com/WebAssembly/gc">WasmGC</a> by default. If you are working with older browser versions, you need to <a href="http
```suggestion
      Make sure that your browser version supports the new <a href="https://github.com/WebAssembly/gc">WasmGC</a> by default. If you are working with older browser versions, <a href="https://kotlinlang.org/docs/wasm-troubleshooting.html#browser-versions">configure the environment</a>.
```

2024-05-10 15:22 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +To publish your web application, you first need to create the artifacts containing the compiled files
```suggestion
To publish your web application, create the artifacts containing the compiled files 
```

2024-05-10 15:22 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +Once the application task completes, you can find the generated artifacts in the `composeApp/build/dist/wasmJs/productionExecutable`
```suggestion
Once the task completes, you can find the generated artifacts in the `composeApp/build/dist/wasmJs/productionExecutable`
```

This word seems forgotten here, unless I misuderstood something.

2024-05-10 15:22 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +With the artifacts ready, you can deploy your application on a web hosting platform. In this example, we use GitHub Pages:
```suggestion
With the artifacts ready, you can deploy your application on a web hosting platform. In this example, we use GitHub Pages:
```
```suggestion
With the artifacts ready, you can deploy your application on the web hosting platform:
```

We mentioned the platform we're using a couple of times already, might be enough. Tell me what you think.

2024-05-10 15:22 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +1. Copy all the contents in your `productionExecutable` directory into the repository where you want to create a site.
```suggestion
1. Copy the contents in your `productionExecutable` directory into the repository where you want to create a site.
```

2024-05-10 15:22 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +your web application, see the [Debug in your browser](https://kotlinlang.org/docs/wasm-debugging.html#debug-in-your-browser)
```suggestion
in the browser, see the [Debug in your browser](https://kotlinlang.org/docs/wasm-debugging.html#debug-in-your-browser)
```

2024-05-13 09:42 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +### On the web
Agree!

2024-05-13 10:58 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +* In the second variant, `composeApplication` is the ID of the container added in your `index.html` file, where the UI is rendered.
I rephrased it. What do you think?

2024-05-14 07:24 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +1. Copy the contents in your `productionExecutable` directory into the repository where you want to create a site.
```suggestion
1. Copy the contents of your `productionExecutable` directory into the repository where you want to create a site.
```

I thought something else was off in this phrase.

2024-05-14 07:27 UTC, zamulla approved these changes
Otherwise all good, thank you!

2024-05-17 15:28 UTC, merged