Spm local integration
JetBrains/kotlin-multiplatform-dev-docs pull request #123
Opened 2024-05-08 17:04 UTC by danil-pavlov

2024-05-13 16:50 UTC, daugeldauge requested changes
We also may have to add an additional step with `embedAndSign` invocation in the build phase to fix the build for a real device. I'll add the details a bit later.

2024-05-13 16:50 UTC, daugeldauge commented on topics/development/multiplatform-spm-local-integration.md
> +## Set up the project
Any version newer than `2.0.0-Beta2` can be used now. So I think this section can be replaced with a small note to use the latest 2.0.0 release candidate.

2024-05-13 16:50 UTC, daugeldauge commented on topics/development/multiplatform-spm-local-integration.md
> +This is useful if you want to simultaneously connect your Kotlin Multiplatform module to several native iOS modules
That's slightly different — the new thing is that we're now able to depend on the Kotlin framework in SPM packages. Previously, it was not possible to do this even in one module.

2024-05-13 16:50 UTC, daugeldauge commented on topics/development/multiplatform-spm-local-integration.md
> +This is useful if you want to simultaneously connect your Kotlin Multiplatform module to several native iOS modules
> native iOS module

Not sure if it's a well-understood terminology. At least for me, it's a bit confusing.

2024-05-13 16:50 UTC, daugeldauge commented on topics/development/multiplatform-spm-local-integration.md
> +> If you have dependencies on other Pods in the `cocoapods` block, you have to keep to the CocoaPods integration approach.
Maybe it's worth expanding here, that it means that the tutorial has no use in this case (meaning that it's impossible for now to depend on pods and reference Kotlin in a multi-module SPM project at the same time)

2024-05-14 14:57 UTC, danil-pavlov commented
@daugeldauge, thank you for all the suggestions! Please check the new version

2024-05-16 16:40 UTC, daugeldauge approved these changes

2024-05-17 08:21 UTC, zamulla approved these changes
👍

2024-05-17 08:21 UTC, merged

2024-07-15 01:01 UTC, markst commented on topics/development/multiplatform-spm-local-integration.md
> +5. Use the code from Kotlin in the local Swift package added to your Xcode project:
Could be worth mentioning about explicitly linking the dependency in the Local Swift Package?
Not sure if project will build if “Find Implicit Dependencies” is disable. 

FYI: https://github.com/swiftlang/swift-package-manager/issues/5297

2024-07-17 09:00 UTC, markst commented on topics/development/multiplatform-spm-local-integration.md
> +5. Use the code from Kotlin in the local Swift package added to your Xcode project:
@daugeldauge so you mean a SPM plugin would be required to prebuild the xcframework in order to be linked? Without using the Run Script Phase.

Using these steps if we were to open the `Package.swift` independently, the package will not compile. 
I believe there needs to be some explanation of this in the readme to explain Xcode finds Implicit Dependencies.

---

Perhaps it's a alternative approach, but manual usage of the assembled framework might be as follows:

5. Build the `XCFramework` using:
   ```bash
   ./gradlew assembleXCFramework
   ```
   This will generate `MyLibrary.xcframework` in the `build/XCFrameworks/release` and `build/XCFrameworks/debug` directories.

6. Link the generated `MyLibrary.xcframework` in your `Package.swift` file:

   ```swift
   // swift-tools-version:5.3
   import PackageDescription

   let package = Package(
       name: "MyPackage",
       platforms: [
           .iOS(.v13)
       ],
       products: [
           .library(
               name: "MyLibrary",
               targets: ["MyLibrary"]
           ),
       ],
       dependencies: [
           // Add the path to the xcframework
           .binaryTarget(
               name: "MyLibrary",
               path: "../path/to/MyLibrary.xcframework"
           ),
       ],
   )
   ```

2024-07-17 09:08 UTC, markst commented on topics/development/multiplatform-spm-local-integration.md
> +5. Use the code from Kotlin in the local Swift package added to your Xcode project:
Something like this?:https://github.com/marty-suzuki/kmm-with-spm-buildtoolplugin-sample/blob/main/iosApp/Modules/plugins/MultiplatformBuildPlugin/MultiplatformBuildPlugin.swift

I believe the sandboxing is only an issue when attempting to write to arbitrary locations in the file system, where as if we perform as task on gradle, I'm not sure it matters? I'll need to investigate