update: 1.6.10-rc01 what's new
JetBrains/kotlin-multiplatform-dev-docs pull request #124
Opened 2024-05-10 12:36 UTC by zamulla

2024-05-10 13:22 UTC, terrakok commented on topics/whats-new/whats-new-compose-eap.md
> +### New Compose compiler Gradle is required for Kotlin 2.0
New Compose compiler Gradle **plugin**

2024-05-14 08:22 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-eap.md
> +### New Compose compiler Gradle is required for Kotlin 2.0
```suggestion
### New Compose compiler Gradle plugin is required for Kotlin 2.0
```

2024-05-14 08:23 UTC, MatkovIvan approved these changes

2024-05-14 08:23 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-eap.md
> +### New Compose compiler Gradle is required for Kotlin 2.0
```suggestion
### New Compose compiler Gradle plugin is required for Kotlin 2.0
```

2024-05-14 12:04 UTC, koshachy requested changes
Some small changes here and there.
Please, take a look.

2024-05-14 12:04 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +for Chinese, Japanese, and Korean.
IDK, will be more readable if we add "languages" in the end of the sentence?
Or it's better to keep it concise?

2024-05-14 12:04 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +Full support and support for other platforms is planned for the 1.7.0 release of Compose Multiplatform.
Let's get read of "of".

Full support and support for other platforms is planned for(or in?) the Compose Multiplatform 1.7.0 release.

2024-05-14 12:04 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +after changing your Kotlin version from 1.9 to 2.0 (or the other way around).
```suggestion
after changing your Kotlin version from 1.9.x to 2.0.0 (or the other way around).
```

2024-05-14 12:04 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +              minimumSystemVersion = "12.0"
```suggestion
                minimumSystemVersion = "12.0"
```

2024-05-15 13:49 UTC, hfhbd commented on topics/whats-new/whats-new-compose-eap.md
> +### New Compose compiler Gradle pliugin is required for Kotlin 2.0
```suggestion
### New Compose compiler Gradle plugin is required for Kotlin 2.0
```

2024-05-16 08:41 UTC, koshachy approved these changes
Minor things, overall is good

2024-05-16 08:41 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +### New Compose compiler Gradle plugin is required for Kotlin 2.0
```suggestion
### New Compose compiler Gradle plugin is required for Kotlin 2.0.0
```

2024-05-16 08:41 UTC, koshachy commented on topics/whats-new/whats-new-compose-eap.md
> +See [the pull request](https://github.com/JetBrains/compose-multiplatform/pull/4271) for details.
Usually we don't make articles as a part of a link

2024-05-16 09:46 UTC, merged