fix: three repos illustration
JetBrains/kotlin-multiplatform-dev-docs pull request #129
Opened 2024-05-13 14:40 UTC by danil-pavlov

2024-05-14 07:20 UTC, zamulla requested changes

2024-05-14 07:20 UTC, zamulla commented on images/config-options/three-repositories.svg
The lines going inside the "Android project" and the "Xcode project" bubbles look like they end in the wrong place, intuitively they should connect with similar lines around the project blocks.

To keep the visual consistent, maybe switch around the styles? So that the "Android app", for example, has the solid border, and the "Android project" is the gray block without the border.

2024-05-14 12:04 UTC, danil-pavlov commented on images/config-options/three-repositories.svg
That was all the designer's decision with the lines and labels, and it's consistent with other diagrams on this page. I can also argue that lines should connect apps (frameworks) and not projects, as they do in case of mono- and two repos. "Android app" and the "Android project" are also different concepts, and it's important to show the difference here when you have a separate Android project

2024-05-23 08:12 UTC, zamulla commented on images/config-options/three-repositories.svg
I finally got to finding the page, all of them are like this, I see :)

2024-05-23 08:13 UTC, zamulla approved these changes
👍

2024-05-30 11:04 UTC, merged