update: mention kotlin-swing-coroutines as potentially necessary for Lifecycle and ViewModel
JetBrains/kotlin-multiplatform-dev-docs pull request #149
Opened 2024-05-29 10:45 UTC by zamulla

2024-05-29 13:31 UTC, MatkovIvan requested changes

2024-05-29 13:31 UTC, MatkovIvan commented on topics/compose/compose-lifecycle.md
> +```
```suggestion
`Lifecycle.coroutineScope` is bound to `Dispatchers.Main.immediate` which might be unavailable on Desktop by default. To make it work correctly with Compose Multiplatform please add the `kotlinx-coroutines-swing` dependency. See [`Dispatchers.Main` docs](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html) for details.
```

2024-05-29 13:31 UTC, MatkovIvan commented on topics/compose/compose-viewmodel.md
> +    ```
```suggestion
3. `ViewModel.viewModelScope` is bound to `Dispatchers.Main.immediate` which might be unavailable on Desktop by default. To make it work correctly with Compose Multiplatform please add the `kotlinx-coroutines-swing` dependency. See [`Dispatchers.Main` docs](https://kotlinlang.org/api/kotlinx.coroutines/kotlinx-coroutines-core/kotlinx.coroutines/-dispatchers/-main.html) for details.
```

2024-05-29 14:31 UTC, MatkovIvan approved these changes

2024-05-31 12:01 UTC, danil-pavlov requested changes

2024-05-31 12:01 UTC, danil-pavlov commented on topics/compose/compose-viewmodel.md
> +> When running coroutines in a `ViewModel`, remember that the `ViewModel.viewModelScope` value is tied to the `Dispatchers.Main.immediate` value
```suggestion
> When running coroutines in a `ViewModel`, remember that the `ViewModel.viewModelScope` value is tied to the `Dispatchers.Main.immediate` value,
```

2024-05-31 13:04 UTC, merged