update: remove the old compatibility section and clarify the platform limitations
JetBrains/kotlin-multiplatform-dev-docs pull request #151
Opened 2024-05-30 10:08 UTC by zamulla

With Kotlin 2.0.0 and the Compose compiler Gradle plugin, there is no need to manually juggle different compiler plugins to try new versions.

2024-05-30 10:14 UTC, igordmn commented on topics/compose/compose-compatibility-and-versioning.md
> +| [1.6.10](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.2)  | 1.6.7                   | 1.2.1                             |
```suggestion
| [1.6.10](https://github.com/JetBrains/compose-multiplatform/releases/tag/v1.6.10)  | 1.6.7                   | 1.2.1                             |
```

2024-05-30 10:26 UTC, igordmn approved these changes

2024-05-31 11:47 UTC, danil-pavlov requested changes

2024-05-31 11:47 UTC, danil-pavlov commented on topics/compose/compose-compatibility-and-versioning.md
> +{type="tip"}
```suggestion
{type="note"}
```

2024-05-31 11:47 UTC, danil-pavlov commented on topics/compose/compose-compatibility-and-versioning.md
> +{type="tip"}
Seems rather important, a grey tip is not that visible

2024-05-31 11:47 UTC, danil-pavlov commented on topics/compose/compose-compatibility-and-versioning.md
> +## Limitations of Compose Multiplatform for Desktop releases
```suggestion
## Limitations of Compose Multiplatform for desktop releases
```

2024-05-31 11:47 UTC, danil-pavlov commented on topics/compose/compose-compatibility-and-versioning.md
> +Compose Multiplatform for Desktop has the following limitations:
```suggestion
Compose Multiplatform for desktop has the following limitations: 
```

2024-05-31 13:06 UTC, danil-pavlov approved these changes

2024-05-31 13:08 UTC, merged