update: reviewing the Wasm tutorial part
JetBrains/kotlin-multiplatform-dev-docs pull request #171
Opened 2024-06-26 12:14 UTC by zamulla

2024-06-28 14:08 UTC, Schahen approved these changes

2024-07-01 09:58 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
Would it be worth it to add a leading line before the desktop app image as well as before the iOS and Android  apps? This is to give context about the opening of the app and provide some transition between the image of the run configuration button and the image of the apps.

This leading line would be  something like:
[Image of run configuration button]
The app opens automatically in the device simulator/preview window:
[Image of the app]

2024-07-01 10:32 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
>  ![Compose Multiplatform UI app](compose-multiplatform-ui-app.png){width=700}
I just downloaded the project agian and noticed that the code in this image, together with the code snippet from  [Implementing composable functions](https://helpserver.labs.jb.gg/help/kotlin-multiplatform-dev/js-timezone/compose-multiplatform-explore-composables.html#implementing-composable-functions) have a small mismatch with the current project that one get from the wizard. The upper line:
`@OptIn(ExperimentalResourceApi::class)` didn't appear to me in the latest project I downloaded. Can you check if it appears to you? Otherwise, should we update it to make it consistent?

2024-07-01 10:50 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
>  ![Compose Multiplatform UI app](compose-multiplatform-ui-app.png){width=700}
Yes, I forgot there's a screenshot of the code. Considering it changes pretty often, I'd remove it entirely, or change it to a codeblock. Thanks for noticing!

2024-07-01 11:00 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +  in the example, the entire document's body works as the container.
```suggestion
  In the example, the entire document's body works as the container.
```

2024-07-01 11:01 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +* The web app is inserted into the container specified as a parameter for the `ComposeViewport` function:
```suggestion
* The web app is inserted into the container specified as a parameter for the `ComposeViewport` function.
```

2024-07-01 11:21 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
> +   wasmJsMain.dependencies {
Can we specify a bit the location in the introductory line? 

Open the composeApp/build.gradle.kts file and add it as a dependency to the project within the `sourceSets{}` block.

2024-07-01 11:22 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
> +   * To support timezones in the web target, the reference to the necessary npm package is included in `wasmJsMain`
```suggestion
   * To support timezones in the web target, the reference to the necessary `npm` package is included in `wasmJsMain`
```

2024-07-01 11:27 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
>  2. Once the dependency is added, you're prompted to resync the project. Click **Sync Now** to synchronize Gradle files:
In step 1 of these instructions 
"Open the App.kt file and add the following function:"
Can we specify the location? It will be very helpful as the previous step is in a location out of the commonMain directory.

2024-07-01 11:51 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
>  2. Once the dependency is added, you're prompted to resync the project. Click **Sync Now** to synchronize Gradle files:
Nothing happens when I click Sync now. Should I restart the project? Later on, I cant' successfully rerun with the modified code 🤔

2024-07-01 11:53 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
> +3. Switch the web app from using an `Element` as a container to the HTML tag with an externally specified `id`:
In step 1 of these instructions
"Open the App.kt file and add the following function:"
Can we specify the location? It will be very helpful as the previous step is in a location out of the commonMain directory.

2024-07-01 11:56 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-modify-project.md
>  2. Once the dependency is added, you're prompted to resync the project. Click **Sync Now** to synchronize Gradle files:
The Sync Now stays and after some minutes the complete build fails. When looking into the console, the build.gradle.kts is the one with errors after the addition of wasmJsMain.dependencies 🤔

2024-07-01 12:05 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-new-project.md
>     ![Time display in the Compose Multiplatform app on Android and iOS](first-compose-project-on-android-ios-5.png){width=500}
Should we add image of this new app in the browser?

2024-07-01 12:05 UTC, AlejandraPedroza requested changes
Great updates! I left some comments.

2024-07-01 13:19 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-modify-project.md
> +   wasmJsMain.dependencies {
We actually have a best practice, to start the code block like this with the topmost Gradle block. I added some code here, should help with the navigation.

2024-07-01 13:21 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-modify-project.md
> +   * To support timezones in the web target, the reference to the necessary npm package is included in `wasmJsMain`
Here "npm" is the proper name of the package manager, like "pip", not the terminal command reference: https://www.npmjs.com/

2024-07-01 13:52 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-new-project.md
>     ![Time display in the Compose Multiplatform app on Android and iOS](first-compose-project-on-android-ios-5.png){width=500}
It's not particularly pretty right now, so I'm investigating the proper way to make it presentable in this example. It's going to be in another PR though.

2024-07-04 12:52 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
>  ## Run your application
I see the added line "The app launches in its own OS window:" in Run your desktop section. It would be helpful to have such a line in Run your app on iOS and Run your app on Android.

2024-07-04 13:02 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
>  ## Run your application
Check out these commits where I tried to clarify that: https://github.com/JetBrains/kotlin-multiplatform-dev-docs/pull/171/files/f728dd5b8202fc96814257a31998eff0b0db5d61..8b29f59bea68f62ab31f24e075cfabfdd06e17f3

2024-07-04 13:29 UTC, AlejandraPedroza commented on topics/compose-onboard/compose-multiplatform-explore-composables.md
> +For web, look at the `main()` function in `composeApp/src/wasmJsMain/kotlin`:
Inside `kotlin` directory there are 2 files. I would say to specify we're referring to the main.kt file.

2024-07-04 18:24 UTC, merged