update: refreshing the "make your Android app run on iOS" tutorial
JetBrains/kotlin-multiplatform-dev-docs pull request #175
Opened 2024-07-03 12:55 UTC by zamulla

2024-07-04 17:45 UTC, danil-pavlov requested changes

2024-07-04 17:45 UTC, danil-pavlov commented on snippets/android-ios-tutorial/ContentView.swift
> -import Shared
It doesn't seem right; recently, we've been using only capitalized import to avoid errors. See other tutorials, [Ktor and SQLDelight](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-ktor-sqldelight.html#create-the-ios-application) and [Share more logic](https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-upgrade-app.html#ios-app)

2024-07-04 17:45 UTC, danil-pavlov commented on topics/multiplatform-integrate-in-existing-app.md
> +   ![iOS run configuration](ios-run-configuration-simplelogin.png){width=269}
fyi, if you want to keep the original size, you can just remove the width parameter

2024-07-04 17:45 UTC, danil-pavlov commented on topics/multiplatform-integrate-in-existing-app.md
> +   2. Add new configuration by clicking the plus sign and choose **iOS Application**.
```suggestion
   2. To add a new configuration, click the plus sign and choose **iOS Application**.
```

2024-07-04 17:45 UTC, danil-pavlov commented on topics/multiplatform-integrate-in-existing-app.md
> +You can close Xcode and rename the `simpleLoginIOS` directory to `iosApp` for consistency with other top-level directories of your
Just a suggestion to make it shorter and more action-focused:

> You can rename ... cross-platform project.
> To do that, close Xcode first and then rename the `simpleLoginIOS` directory to `iosApp` . If you rename the folder with Xcode open, you'll get a warning.

2024-07-04 17:45 UTC, danil-pavlov commented on topics/multiplatform-integrate-in-existing-app.md
> +7. The wizard will create the Kotlin Multiplatform shared module, update the configuration files, and create sample code
The first sentence doesn't seem to be related to the action in step 7. I suggest moving it to step 6. And step 7 could start with "In the root `build.gradle.kts` file, add these aliases for Gradle to resolve the added plugins successfully:" to avoid the 'have to' modal construction

2024-07-04 18:23 UTC, zamulla commented on snippets/android-ios-tutorial/ContentView.swift
> -import Shared
I think it's exactly because the sample is old, yes. I'll suggest changing the `baseName` of the framework to `Shared`.

2024-07-05 04:36 UTC, zamulla commented on snippets/android-ios-tutorial/ContentView.swift
> -import Shared
Done: https://github.com/Kotlin/kmm-integration-sample/pull/26

2024-07-08 12:39 UTC, danil-pavlov approved these changes

2024-07-09 10:23 UTC, merged