update: 2.0.20 update to the composeCompiler {} block
JetBrains/kotlin-multiplatform-dev-docs pull request #199
Opened 2024-08-15 11:03 UTC by zamulla

Some options were move to the `featureFlags` set.

2024-08-15 15:18 UTC, ShikaSD commented on topics/compose/compose-compiler.md
> +> It is strongly recommended that you update your Compose app created with Kotlin 2.0.0 to version 2.0.10 or later. The Compose
```suggestion
> It is strongly recommended that you update your multiplatform Compose app created with Kotlin 2.0.0 to version 2.0.10 or later. The Compose
```

2024-08-15 15:18 UTC, ShikaSD commented on topics/compose/compose-compiler.md
> +#### includeSourceInformation
This option is enabled for Android platform by default

2024-08-15 15:18 UTC, ShikaSD commented on topics/compose/compose-compiler.md
> +#### includeTraceMarkers
Enabled by default since 2.0.20 (and was enabled by default pre 2.0)

2024-08-15 15:18 UTC, ShikaSD commented on topics/compose/compose-compiler.md
> +Strong Skipping mode improves the runtime performance of your application by skipping unnecessary invocations
```suggestion
Strong Skipping mode improves the runtime performance of your application by applying optimizations previously reserved only for stable values.
```

2024-08-19 08:12 UTC, sarahhaggarty requested changes
I found a couple typos but the rest of my suggestions are minor and made to improve the flow or for conciseness :)

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +   * Feature flags enabling or disabling new and experimental features which eventually should become baseline.
```suggestion
   * Feature flags that enable or disable new and experimental features, which should eventually become part of the baseline.
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +An example of such a configuration:
```suggestion
Here's an example configuration:
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +are rolled out and deprecated continuously.
```suggestion
Feature flags are organized into a separate set to minimize changes to top-level properties as new flags
are continuously rolled out and deprecated.
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +To disable a feature flag that is enabled by default, call the `disabled()` function for it, for example:
```suggestion
To disable a feature flag that is enabled by default, call the `disabled()` function on it, for example:
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +with comparisons of the `$changed` meta parameter when possible.
```suggestion
Intrinsic remember is an optimization mode that inlines `remember` invocations and, where possible, replaces `.equals` comparisons for keys with comparisons of the `$changed` meta parameter.
```
Shouldn't it be `.equals()` ?

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +> This feature is considered [Experimental](supported-platforms.md#core-kotlin-multiplatform-technology-stability-levels) and is thus disabled by default.
```suggestion
> This feature is considered [Experimental](supported-platforms.md#core-kotlin-multiplatform-technology-stability-levels) and is disabled by default.
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +of composable functions whose parameters haven't changed.
```suggestion
Strong Skipping mode improves the runtime performance of your application by applying optimizations previously reserved only for stable values of composable functions whose parameters haven't changed.
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +For example, composables with unstable parameters become skippable, and lambdas with unstable captures are memoized.
```suggestion
For example, composables with unstable parameters become skippable, and lambdas with unstable captures are memorized.
```

2024-08-19 08:12 UTC, sarahhaggarty commented on topics/compose/compose-compiler.md
> +in the Kotlin GitHub repo.
```suggestion
in the Kotlin GitHub repository.
```

2024-08-19 11:45 UTC, sarahhaggarty approved these changes
LGTM! 🚀  (When appropriate 😉 )

2024-08-22 15:24 UTC, merged