feature: external drag and drop in Compose Multiplatform for desktop
JetBrains/kotlin-multiplatform-dev-docs pull request #207
Opened 2024-08-28 17:37 UTC by zamulla

2024-09-05 13:38 UTC, zamulla commented on topics/compose/compose-drag-drop.md
> +            println("Action at the target: ${event.action}")
There is no need, but it felt nice to immediately see in the log that it works as advertised, without the need to set up debugging output by myself. If this was more than a couple of lines, I'd probably find it cumbersome, but as it is, no big deal.

2024-09-05 14:00 UTC, zamulla commented on topics/compose/compose-drag-drop.md
> +you can use the `dragAndDropSource` and `dragAndDropTarget` modifiers to specify potential sources or destinations for drag operations.
It's hard not to focus on drag and drop when that is the title of the page and the name of the API :)

I rewrote the paragraph a little more towards the abstract. "Sharing" intuitively is more like something that is happening behind the scenes (at least in the Apple ecosystem experience). I also tried "transfer" for size, but that made it sound network-adjacent.

2024-09-06 13:58 UTC, danil-pavlov requested changes

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +[//]: # (title: Drag and drop operations)
Here and below, "drag and drop" should be hyphenated when used as an adjective, drag-and-drop operations, drag-and-drop session, target, and so on

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +        drawDragDecoration = {
Indentation inside drawDragDecoration is 3 spaces, not 4

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +        // Creates a visual representation for the data being dragged
```suggestion
        // Creates a visual representation of the data being dragged
```

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +                        // or to interpret user's expectations.
I think it works without possessive too, up to you

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +3. Write the necessary overrides: for example, `onDrop` for parsing the received data, or `onEntered` when a draggable
```suggestion
3. Write the necessary overrides: for example, `onDrop` for parsing the received data or `onEntered` when a draggable
```

2024-09-06 13:58 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +For more implementation details and common use cases, see the [Drag and drop](https://developer.android.com/develop/ui/compose/touch-input/user-interactions/drag-and-drop) article about the correspon
```suggestion
For more details on implementation and common use cases, see the [Drag and drop](https://developer.android.com/develop/ui/compose/touch-input/user-interactions/drag-and-drop) article about the corresponding modifiers
```

2024-09-06 15:14 UTC, danil-pavlov approved these changes

2024-09-06 15:14 UTC, danil-pavlov commented on topics/compose/compose-drag-drop.md
> +[//]: # (title: Drag and drop operations)
The top title should also be fixed, otherwise LGMT

2024-09-10 09:57 UTC, merged