feat: byte array image converters in Compose Multiplatform 1.7.0
JetBrains/kotlin-multiplatform-dev-docs pull request #209
Opened 2024-08-30 12:13 UTC by zamulla

2024-08-30 15:19 UTC, terrakok requested changes

2024-08-30 15:19 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +Image(bytes.decodeToImageVector(Density(1f, 1f)), null)
Image(bytes.decodeToImageVector(LocalDensity.current), null)

2024-08-30 15:19 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +Image(bytes.decodeToSvgPainter(Density(1f, 1f)), null)
Image(bytes.decodeToSvgPainter(LocalDensity.current), null)

2024-09-02 16:19 UTC, terrakok approved these changes

2024-09-03 08:11 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
> +If the file you are reading is a bitmap (JPEG, PNG, BMP, WEBP) or an XML vector image, you can use these functions
```suggestion
If the file you are reading is a bitmap (JPEG, PNG, BMP, WEBP) or an XML vector image, you can use the following functions
```

2024-09-03 08:12 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
> +If the file you are reading is a bitmap (JPEG, PNG, BMP, WEBP) or an XML vector image, you can use these functions
We're talking about the functions in the example, right? Otherwise, only "these" it's a bit confusing because we haven't mentioned any other functions in this section.

2024-09-03 08:14 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
> +// bytes = Res.readBytes("files/example.png")
Can we make the code comments a bit more descriptive? For example, as stated in our SG, with a verb in 3rd form to indicate the action performed by the code line.

2024-09-03 08:17 UTC, AlejandraPedroza reviewed
Looks good, left some comments.

2024-09-03 10:55 UTC, zamulla commented on topics/compose/compose-images-resources.md
> +// bytes = Res.readBytes("files/example.png")
I added a clarification before the code blocks, these comments are more to signify that it's not worth it to repeat the coroutined code from the previous section.

2024-09-03 12:26 UTC, AlejandraPedroza approved these changes
LGTM 🚀

2024-09-03 13:47 UTC, merged