feat: setting custom resource directories in Gradle
JetBrains/kotlin-multiplatform-dev-docs pull request #210
Opened 2024-08-30 12:14 UTC by zamulla

2024-08-30 15:17 UTC, terrakok requested changes

2024-08-30 15:17 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +
delete

2024-08-30 15:17 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +            sourceSetName = "jvmMain",
better: `sourceSetName = "iosMain",`

2024-09-03 08:23 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
> +An example configuration can look like this:
```suggestion
An example configuration looks like this:
```

2024-09-03 08:25 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
>    when the resource library is only available transitively. By default, the `auto` value is used, to generate the `Res`
```suggestion
  when the resource library is only available transitively. By default, the `auto` value is used to generate the `Res`
```

2024-09-03 08:26 UTC, AlejandraPedroza commented on topics/compose/compose-images-resources.md
> +            sourceSetName = "iosMain",
Is this indentation correct?

2024-09-03 08:27 UTC, AlejandraPedroza reviewed
Look good! Just minor comments to consider.

2024-09-03 11:01 UTC, zamulla commented on topics/compose/compose-images-resources.md
> +            sourceSetName = "iosMain",
Nope!

2024-09-03 11:24 UTC, zamulla commented on topics/compose/compose-images-resources.md
> +You can also set up a folder populated by a Gradle task, for example, with [downloaded files](#remote-files):
I think I got confused here, removed the link now.

2024-09-03 12:30 UTC, AlejandraPedroza approved these changes
LGTM 👍

2024-09-03 12:40 UTC, merged