feat: move mouse events from github
JetBrains/kotlin-multiplatform-dev-docs pull request #214
Opened 2024-09-02 02:36 UTC by ElviraMustafina

- separate page for mouse events
- new gifs
- minor updates to code samples: added titles for windows, aligned some elements, removed unused imports

note: the topic is temporarily placed top-level inside "Compose Multiplatform UI framework", I'll move it under "Desktop-specific components" when other parts are ready

2024-09-04 08:55 UTC, m-sasha commented on topics/compose/compose-desktop-mouse-events.md
> +        }.size(200.dp)
Reformatting:
```
        Box(modifier = Modifier
            .offset {
                IntOffset(topBoxOffset.x.toInt(), topBoxOffset.y.toInt())
            }
            .size(200.dp)
```

2024-09-04 08:55 UTC, m-sasha commented on topics/compose/compose-desktop-mouse-events.md
> +                        enabled = true,
What is the point of specifying it explicitly?

2024-09-04 08:55 UTC, m-sasha commented on topics/compose/compose-desktop-mouse-events.md
> +        }.size(200.dp)
Reformat like above.

2024-09-04 08:55 UTC, m-sasha commented on topics/compose/compose-desktop-mouse-events.md
> +    }.size(200.dp)
Also reformat

2024-09-06 12:46 UTC, zamulla requested changes
Nice job! I left some suggestions.

2024-09-06 19:30 UTC, ElviraMustafina commented on topics/compose/compose-desktop-mouse-events.md
> +In your desktop project, you can listen to various mouse events, like clicking, moving, scrolling, entering, and exiting.
Let's try "input region" instead

2024-09-10 15:20 UTC, zamulla approved these changes
Thanks! Approved, just one more suggestion to take into account.

2024-09-10 16:05 UTC, merged