feat: new page for windows management
JetBrains/kotlin-multiplatform-dev-docs pull request #223
Opened 2024-09-10 09:55 UTC by ElviraMustafina

- separate page for top-level windows management
- new gifs
- minor updates to code samples like titles for windows

note: the topic is temporarily placed top-level inside "Compose Multiplatform UI framework", I'll move it under "Desktop-specific components" when other parts are ready

2024-09-17 10:31 UTC, m-sasha approved these changes

2024-09-18 10:22 UTC, zamulla requested changes
Huge work! Some suggestions and questions in the comments.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +`singleWindowApplication` is a function for the simplified creation of a single window application:
To get rid of nominalizations as much as possible, I would rephrase here to something like "You can create a single window application by calling the `singleWindowApplication` function". And if the "easier to use" paragraph has been moved above, we don't need to mention that it is easier again.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +To change the window state, use callbacks or observe it in composables. Any change of the state triggers automatic recomposition.
I think the order here would be more natural with "Any change..." first and "To change the window state..." second. And then a colon after the second sentence to transition into the code block.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +If you need to react to the state changes and send a value to another non-composable application level, for example, write it to the database, you can use `snapshotFlow`.
```suggestion
If you need to react to the state changes and send a value to another non-composable application level, for example, write it to the database, you can use the `snapshotFlow()` function. 
```

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +The `snapshotFlow` function captures the current value of a composable's state.
```suggestion
This function captures the current value of a composable's state.
```

If the previous suggestion is applied, so as not to repeat the name twice.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +        // Content
Not sure what this comment is about :)

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +The following code sample demonstrates how to use these composables to combine both regular and modal windows:
```suggestion
The following code sample demonstrates how to use these composables to combine regular and modal windows:
```

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +                // Content
I can _guess_ what this comment is about, but it could be more transparent.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +If you want to add a custom draggable title bar to the undecorated window or make the whole window draggable, you can use the `WindowDraggableArea` composable:
```suggestion
To add a custom draggable title bar to the undecorated window or make the whole window draggable, you can use the `WindowDraggableArea` composable:
```

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +`WindowDraggableArea` can be used inside `singleWindowApplication`, `Window`, and `DialogWindow` only. To use it in another composable function, pass `WindowScope` as a receiver:
```suggestion
`WindowDraggableArea` can be used inside `singleWindowApplication()`, `Window()`, and `DialogWindow()` composables only. To use it in another composable function, pass a `WindowScope()` function as a receiver:
```

Unless it is clearly detrimental, we use regular nouns so that the grammar doesn't depend on the user knowing the objects behind the names by heart or figuring it out in context.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +            undecorated = true, // Transparent window must be undecorated
Let's move the comments to a separate line in this sample, too.

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +You can also access `ComposeWindow` in the composable `Window` scope:
As I don't see these names in the code sample, it is unclear how it illustrates this statement. Maybe we should add some context here?

2024-09-18 10:22 UTC, zamulla commented on topics/compose/compose-desktop-top-level-windows-management.md
> +Explore the tutorials about [other desktop components](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials#desktop).
Should we continue to link GitHub here? I think all of the tutorials are listed in the KMP docs now?

2024-09-18 16:04 UTC, ElviraMustafina commented on topics/compose/compose-desktop-top-level-windows-management.md
> +        // Content
Changed to "Content of the window" everywhere

2024-09-18 16:05 UTC, ElviraMustafina commented on topics/compose/compose-desktop-top-level-windows-management.md
> +Explore the tutorials about [other desktop components](https://github.com/JetBrains/compose-multiplatform/tree/master/tutorials#desktop).
Not yet!

2024-09-19 08:27 UTC, zamulla approved these changes
👍 

There are still build problems with the anchors (because of the changed headers), don't forget to fix them before merging :)

2024-09-19 21:04 UTC, merged