chore: multiplatform resources page restructured
JetBrains/kotlin-multiplatform-dev-docs pull request #227
Opened 2024-09-12 08:42 UTC by zamulla

2024-09-13 12:25 UTC, danil-pavlov requested changes

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-usage.md
> +Multiplatform resources as Android assets also allow directly accessing them on Android from WebViews and media player components,
```suggestion
Using Multiplatform resources as Android assets also means direct access from WebViews and media player components on Android
```

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-usage.md
> +since resources can be reached by a simple path, for example `Res.getUri(“files/index.html”)`
```suggestion
since resources can be reached by a simple path, for example `Res.getUri("files/index.html")`.
```

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-usage.md
> +### Using Java resources with Compose Multiplatform
```suggestion
### Using Java resources
```

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-usage.md
> +### Using Java resources with Compose Multiplatform
Some headers are to big for the right-side menu, I think this one can be safely shortened

2024-09-13 12:25 UTC, danil-pavlov commented on mpd.tree
> +            <toc-element id="compose-resources-setup.md"/>
I think shorter titles can be used here to avoid two-line titles in the left menu, like "Setup and configuration" and "Resource usage"

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-setup.md
> +
I feel like the page now doesn't have an intro, explaining both the project setup and qualifiers. for example, the overall structure could be:
```
<intro>
## Project setup
To access resources in your multiplatform projects,...
### Custom dirs
## Qualifiers
## Publication
```

2024-09-13 12:25 UTC, danil-pavlov commented on topics/compose/compose-resources-usage.md
> +When you've [set up the resources for your project](compose-resources-setup.md),
I feel like now this intro is only concerned with the Res class generation and doesn't mention other important sections on the page, consider adding another paragraph, for example:

```
When you've set up the resources for your project, first generate the special Res class, which provides access to resources. 

To generate the Res class and all the resource accessors, build the project or re-import the project in the IDE.

<a paragraph about different resources usage and accessing external resources>

## Class generation settings﻿

You can also customize the generated class to suit your needs using the Gradle settings.

In the compose.resources {} block, ...
```

2024-09-18 12:52 UTC, zamulla commented on topics/compose/compose-resources-usage.md
> +When you've [set up the resources for your project](compose-resources-setup.md),
True, true. I adjusted the beginning mostly like you suggested.

2024-09-18 13:53 UTC, zamulla commented on topics/compose/compose-resources-setup.md
> +
Agreed, refactored the beginning of the page here as well.

2024-09-18 16:02 UTC, danil-pavlov requested changes
Thank you! just a few comments left

2024-09-18 16:02 UTC, danil-pavlov commented on topics/compose/compose-multiplatform-resources-usage.md
> +To learn about passing multiplatform resources to external libraries and about using Java resources and remote files
Previous paragraphs don't have links to the corresponding sections. I think we can avoid it there too, creating just a general description of the process, for example:

> After that, you can use the generated class to access multiplatform resources from your project or from external libraries﻿ or other resources.

2024-09-19 07:11 UTC, zamulla commented on topics/compose/compose-multiplatform-resources-usage.md
> +To learn about passing multiplatform resources to external libraries and about using Java resources and remote files
Yes, I think the ToC can do its job here. In the end I think these "other resources" don't fit into a summary, because they are not related to Compose functionality really, so I left them out.

2024-09-19 11:59 UTC, merged