feat: new Swing interop page
JetBrains/kotlin-multiplatform-dev-docs pull request #231
Opened 2024-09-16 11:00 UTC by ElviraMustafina

- new page for Swing interop
- new gifs
- minor updates to code samples: added titles for windows, removed unused imports

2024-10-08 10:15 UTC, m-sasha requested changes
We should also document our new flags:
- `compose.swing.render.on.graphics`
- `compose.layers.type`
- `compose.interop.blending`

2024-10-08 10:15 UTC, m-sasha commented on topics/compose/compose-desktop-swing-interoperability.md
> +Compose Multiplatform renders all its content using a single heavyweight Swing component and relies on logical rendering layers, while Swing operates using both heavyweight and lightweight components
> while Swing operates using both heavyweight and lightweight components (`Component`/`JComponent`)

That's neither correct, nor very important. 
- Swing actually has the same approach as Compose - they both render all their content on a single "system" (heavyweight) component. Swing's "lightweight" components roughly correspond to Compose element nodes, in the sense that they are virtual, rather than system, components. The difference is that Compose renders using a different rendering engine (Skia), but I don't think that's important here.
- `Component` is not heavyweight. Some of its subclasses are heavyweight.
- Swing mostly operates using lightweight components, with a single heavyweight (the window) in the root.

2024-10-08 10:15 UTC, m-sasha commented on topics/compose/compose-desktop-swing-interoperability.md
> +Therefore, consider replacing these components with Swing-based implementations.
We have a new, experimental mode, where popups (and tooltips, context menus) are created as system windows. It's worthwhile to document it. @MatkovIvan

2024-10-08 10:15 UTC, m-sasha commented on topics/compose/compose-desktop-swing-interoperability.md
> +Compose Multiplatform renders all its content using a single heavyweight Swing component and relies on logical rendering layers, while Swing operates using both heavyweight and lightweight components
We also have an experimental mode where Compose is rendered on a Swing component directly, which improves the layering of Swing and Compose elements. @MatkovIvan

2024-10-08 10:29 UTC, MatkovIvan commented on topics/compose/compose-desktop-swing-interoperability.md
> +Compose Multiplatform renders all its content using a single heavyweight Swing component and relies on logical rendering layers, while Swing operates using both heavyweight and lightweight components
See [Render to swing graphics](https://blog.jetbrains.com/kotlin/2023/08/compose-multiplatform-1-5-0-release/#enhanced-swing-interop)

2024-10-08 10:29 UTC, MatkovIvan commented on topics/compose/compose-desktop-swing-interoperability.md
> +Therefore, consider replacing these components with Swing-based implementations.
See [Popup/Dialog as a separate view or window](https://www.jetbrains.com/help/kotlin-multiplatform-dev/whats-new-compose.html#desktop-experimental)

2024-10-24 03:31 UTC, ElviraMustafina commented on topics/compose/compose-desktop-swing-interoperability.md
> +Compose Multiplatform renders all its content using a single heavyweight Swing component and relies on logical rendering layers, while Swing operates using both heavyweight and lightweight components
Added "Experimental off-screen rendering﻿" and "Experimental separate views for popups"

2024-10-24 03:31 UTC, ElviraMustafina commented on topics/compose/compose-desktop-swing-interoperability.md
> +Therefore, consider replacing these components with Swing-based implementations.
Added "Experimental interop blending"

2024-11-07 20:06 UTC, m-sasha approved these changes

2024-11-07 20:06 UTC, m-sasha commented on topics/compose/compose-desktop-swing-interoperability.md
> +System.setProperty("compose.swing.render.on.graphics", "true")
It's important to set this at the start of your application, before calling any Compose code. It's even better to set it via the command that runs the JVM by passing `-Dcompose.swing.render.on.graphics=true` to it.

2024-11-08 09:25 UTC, MatkovIvan approved these changes

2024-11-08 09:25 UTC, MatkovIvan commented on topics/compose/compose-desktop-swing-interoperability.md
> +To enable this experimental feature, use the `compose.interop.blending` system property:
Please copy a note about "The property must be set before executing any Compose code in your application" here too

2024-11-11 13:04 UTC, zamulla requested changes
Nice!

I think we could make the purpose of the article a bit clearer, left some suggestions about that.

2024-11-13 05:39 UTC, ElviraMustafina commented on topics/compose/compose-desktop-swing-interoperability.md
> +To enable this experimental feature, use the `compose.interop.blending` system property:
@MatkovIvan Should we also recommend to set it via the command line?

2024-11-25 13:07 UTC, MatkovIvan commented on topics/compose/compose-desktop-swing-interoperability.md
> +To enable this experimental feature, use the `compose.interop.blending` system property:
It's a valid option, but the main point is that it should be set before Compose.
Not sure if we need to describe all ways to set it for each flag. This part is up to you

2024-11-25 14:01 UTC, ElviraMustafina commented on topics/compose/compose-desktop-swing-interoperability.md
> +To enable this experimental feature, use the `compose.interop.blending` system property:
Thanks! I added info about both options, just in case.

2024-11-28 09:13 UTC, zamulla approved these changes
All good, thank you! The only minor thing is that code comments should be written in third person according to the Kotlin guidelines, but no notes otherwise.

2024-11-29 00:37 UTC, merged