new page for keyboard events
JetBrains/kotlin-multiplatform-dev-docs pull request #266
Opened 2024-10-29 11:07 UTC by ElviraMustafina

- new page for keyboard events
- new gifs with visible branding 
- updated code samples: added titles for windows, removed unused imports and experimental opt-ins, replaced deprecated `Dialog()`

2024-11-15 13:23 UTC, igordmn approved these changes

2024-11-15 14:42 UTC, zamulla requested changes
Nice job! Left a couple of consistency suggestions.

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +* Event handlers in the window scope
I would err on the side of "let's put a period at the end of list items here". They are not exactly complete sentences, but long enough.

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +This approach implies that a key pressed on a hardware keyboard is handled as an event for the currently focused component.
Is the word "hardware" pertinent here? For example, when we discuss phone simulators and real devices, there are salient differences in how we use them; if an emulated keyboard would not make a difference here, it may only confuse people to mention hardware specifically.

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +This approach implies that a key pressed on a hardware keyboard is handled as an event for the currently focused component.
I would also rephrase away from passive voice. Maybe it's not that interesting who pressed the key, but it's nice to know the entity that handles key presses (Compose Multiplatform, probably?)

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +it is not consumed: `onPreviewKeyEvent` dispatches the event to its first child, and `onKeyEvent` dispatches the event to the composable's parent.
This sentence runs a bit long and introduces two different concepts: dispatch order and a recommendation for defining shortcuts. I would divide it into two — first, explain the difference between modifiers we introduced in the previous sentence, then, tie that difference to a practical application.

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +The following sample demonstrates `TextField` interactions with the different actions depending on
```suggestion
The following sample demonstrates `TextField` interactions with different actions depending on
```

2024-11-15 14:42 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
So far we called `onPreviewKeyEvent ` and `onKeyEvent ` callbacks and modifiers, now they are also properties. While these are all correct, I think we should pick a default and use something else only when it is beneficial in context.

I guess "callback" is the best default? "Modifiers" I usually reserve for functions of the [Modifier](https://developer.android.com/reference/kotlin/androidx/compose/ui/Modifier) interface — there's a lot of them and they may be easy to confuse with something else. But tell me what you think about this use case in particular.

2024-11-18 11:44 UTC, ElviraMustafina commented on topics/compose/compose-desktop-keyboard.md
> +it is not consumed: `onPreviewKeyEvent` dispatches the event to its first child, and `onKeyEvent` dispatches the event to the composable's parent.
I divided it and moved to the second section, as it makes more sense for a bigger scope: order of the `onPreviewKeyEvent()` lambda calls allows implementing even screen-wide keyboard shortcuts.

2024-11-18 11:46 UTC, ElviraMustafina commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Then they are literally modifiers!
`fun Modifier.onPreviewKeyEvent(onPreviewKeyEvent: (KeyEvent) -> Boolean): Modifier`

2024-11-19 08:56 UTC, igordmn commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Properties in Window aren't modifiers, they are parameters:
```
Window(onPreviewKeyEvent = , onKeyEvent  = )
```

2024-11-20 03:19 UTC, ElviraMustafina commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Only in this part or everywhere? 
I refer to them as modifiers in the first section, with the example `Modifier.onPreviewKeyEvent`,
and as parameters in the second section, with the following example:
```
DialogWindow(onCloseRequest = { isDialogOpen = false },
            title = "Dialog",
            onPreviewKeyEvent = { ...
```

2024-11-25 04:54 UTC, igordmn commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Also, preferable to use `parameter`, not `property`. `Property` in Kotlin has different meaning (for example, `window.onPreviewKeyEvent = ` is a property)

2024-11-25 04:58 UTC, igordmn commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Also, better to not use `callback` in this section, because we need to emphasis that we need to pass a parameter, not a modifier which we passed in the first section.

2024-11-25 15:17 UTC, ElviraMustafina commented on topics/compose/compose-desktop-keyboard.md
> +To define keyboard event handlers that are always active within the current window, use the `onPreviewKeyEvent` and `onKeyEvent` properties,
Thanks for the details! Then the current version is fine: no `callbacks`, no `properties`; `parameters` when passed as parameters, and `modifiers` when used with Modifier.

2024-11-28 09:18 UTC, zamulla approved these changes
Thanks! One more tiny suggestion, but LGTM overall.

2024-11-28 09:18 UTC, zamulla commented on topics/compose/compose-desktop-keyboard.md
> +They differ in where the event is dispatched when it is not consumed: `onPreviewKeyEvent` dispatches the event to its first child,
```suggestion
They differ in how the event is dispatched when it is not consumed: `onPreviewKeyEvent` dispatches the event to its first child, 
```

A nitpicky edit, I just don't think a spatial metaphor is clear here.

2024-11-29 00:40 UTC, merged