Kt 67535 compose desktop accessibility
JetBrains/kotlin-multiplatform-dev-docs pull request #269
Opened 2024-11-05 03:48 UTC by ElviraMustafina

- example with NVDA speech viewer
- skipped the HiDPI issues section: HiDPI support is now included in JDK, and the workaround is no longer needed (and also no longer available in the newer version of NVDA)

2024-11-15 21:05 UTC, ElviraMustafina commented on topics/compose/compose-desktop-accessibility.md
> +<img src="compose-desktop-accessibility.png" alt="Custom button with semantic rules" width="600"/>
I added a screenshot with Accessibility Inspector and a few details about NVDA and JAWS.

2024-11-15 21:27 UTC, igordmn approved these changes

2024-11-28 10:06 UTC, zamulla requested changes
Overall great, thanks! There are a couple of smaller issues I'd like to address.

2024-11-28 10:06 UTC, zamulla commented on topics/compose/compose-desktop-accessibility.md
> +To test the application's accessibility on macOS, you can use [Accessibility Inspector](https://developer.apple.com/documentation/accessibility/accessibility-inspector)
I feel that "test accessibility" is too broad here, maybe "test the custom semantics"?

2024-11-29 01:39 UTC, ElviraMustafina commented on topics/compose/compose-desktop-accessibility.md
> +To enable it, run the following command:
I'm actually not sure about this one.
@igordmn  Do we need JAB only for developers or users of our future app as well?

2024-11-29 02:56 UTC, igordmn commented on topics/compose/compose-desktop-accessibility.md
> +To enable it, run the following command:
This is about developer machine.

For user machine we have a task https://youtrack.jetbrains.com/issue/CMP-373/Accessibility-doesnt-work-on-Windows-when-we-create-a-native-distribution

2024-11-29 15:20 UTC, igordmn commented on topics/compose/compose-desktop-accessibility.md
> +To enable it, run the following command:
I found a way of enabling it on a user machine, but it needs verification:
https://youtrack.jetbrains.com/issue/CMP-373/Accessibility-doesnt-work-on-Windows-when-we-create-a-native-distribution#focus=Change-27-11130024.0-0

2024-12-01 01:42 UTC, ElviraMustafina commented on topics/compose/compose-desktop-accessibility.md
> +To enable it, run the following command:
Updated version: "To develop accessibility features on Windows, enable Java Access Bridge..."
I'll add info about the user's side once [CMP-373](https://youtrack.jetbrains.com/issue/CMP-373) is fixed.

2024-12-03 11:20 UTC, zamulla approved these changes
🎉

2024-12-03 11:25 UTC, merged