feat: new page for context menus
JetBrains/kotlin-multiplatform-dev-docs pull request #273
Opened 2024-11-13 05:19 UTC by ElviraMustafina

- new page for context menus
- new screenshots
- minor updates to code samples: added titles for windows, updated comments
- added info about localization

2024-11-15 13:12 UTC, igordmn commented on topics/compose/compose-desktop-context-menus.md
> +behavior of other parts of the application, you can use the `JPopupTextMenu` class. In this class, `TextContextMenu` uses
```suggestion
behavior of other parts of the application, you can use the `JPopupTextMenu` class. In this class, `LocalTextContextMenu` uses 
```

2024-11-18 14:01 UTC, ElviraMustafina commented on topics/compose/compose-desktop-context-menus.md
> +import androidx.compose.foundation.ContextMenuDataProvider
Applying the patch somehow failed, so I updated the code sample manually.

2024-12-02 16:03 UTC, zamulla requested changes
Nice! There are small suggestions for text, but the most important one is about structure: separating the text context menus from everything else.

2024-12-02 16:03 UTC, zamulla commented on topics/compose/compose-desktop-context-menus.md
> +the right mouse click will trigger the appearance of a context menu:
The intro to this page talks about support for text context menus, and I'm under the impression that this is all Compose can do for desktop, but here we can create a context menu for anything. First, I would make it clearer in the intro, that we can have context menus everywhere; second, maybe put more abstract examples first (this one and theming), and put everything else in a separate section dedicated to text? Right now everything is on the same level of header structure and may be disorienting.

2024-12-16 13:43 UTC, zamulla commented on topics/compose/compose-desktop-context-menus.md
> +## Localized menu items
Should this be moved to the beginning as well, before we get to text context menus?

2024-12-17 01:40 UTC, merged