update: ios project configuration and running
JetBrains/kotlin-multiplatform-dev-docs pull request #33
Opened 2023-11-29 13:11 UTC by danil-pavlov

2023-11-30 12:02 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +* The iOS device registered in Xcode
“The” → “A” here, to match the indefinite article from the intro, right? Otherwise, the meaning muddles a little, and it may seem we're talking about some specific device.

2023-11-30 16:23 UTC, evilya commented on topics/multiplatform-publish-apps.md
> +  2. In your terminal, run `./cleanup.sh`.
`cleanup.sh` is specific to [compose multiplatform template project](https://github.com/JetBrains/compose-multiplatform-template/blob/main/cleanup.sh)
it's not generated in a project from wizard at kmp.jetbrains.com

2023-12-01 08:39 UTC, zamulla requested changes
I ran the scenario about five times to be sure I'm not missing anything, so I have a lot to say on the subject :) correct me if I misunderstood the context anywhere.

2023-12-01 08:39 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +1. Connect a real iPhone device.
On that note, is it worth it to at least summarize in the beginning what needs to be done to register a device in Xcode? Connecting with a cable and turning on Developer mode are things I learned by googling rather than reading that wall of text on the Apple doc page.

2023-12-01 08:39 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +* To configure the `APP_NAME` option, which sets the target executable and application bundle name, open `Config.xcconfig` in any
I would put the condition before the action: “If you haven't opened the project in Android Studio yet, you can change the option in the config directly” or something to that effect.

2023-12-01 08:39 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +  2. In your terminal, run `./cleanup.sh`.
Does this need context as to where exactly the command should be run?

2023-12-01 08:39 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +  3. Change the `APP_NAME` option.
I really want to say “...in any other text editor” here :)

2023-12-01 08:39 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +2. In the `iosApp/Configuration/Config.xcconfig` file, set your `TEAM_ID`.
To reiterate: this is optional if I specify the team in Xcode.

2023-12-01 08:39 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +6. In the **Team** list, select your team.
I think the outcome here does not match the subsection title, and it's the title that's the problem. What the reader should achieve is not finding their Team ID, but associating their project with a Team ID. And this can be done in two ways:
* Run kdoctor, get the ID, and paste it into `Configuration/Config.xcconfig`.
* Open the project in Xcode and choose a team on the **Signing & Capabilities** screen.

After doing either, I can be sure that the project will run on my physical device.

2023-12-04 15:18 UTC, danil-pavlov commented on topics/multiplatform-publish-apps.md
> +  2. In your terminal, run `./cleanup.sh`.
Does it mean it's impossible to change `APP_NAME` after opening the project in AS if the project was created using the KMM plugin or the web wizard?

2023-12-05 11:38 UTC, evilya commented on topics/multiplatform-publish-apps.md
> +  2. In your terminal, run `./cleanup.sh`.
It's possible to change it, but the process is different for projects from web wizard and KMM plugin wizard.
- For a project from the web wizard, changing `APP_NAME` in `Config.xcconfig` and just reopening a project in Android Studio seems enough. At least it seems to work in my case. It's better to check with KMM plugin developers or whoever wrote that guide in the first place, but I believe that actions in `./cleanup.sh` are not necessary, but there might be some tricky scenarios. 
- For project created by KMM plugin, there's no `Config.xcconfig` file at all, so if one wants to change the bundle name, they can to edit `CFBundleName` property in `Info.plist` file.

2023-12-05 12:22 UTC, danil-pavlov commented on topics/multiplatform-publish-apps.md
> +  2. In your terminal, run `./cleanup.sh`.
OK, thank you for clarification! I'll update it in accordance with the web wizard scenario for now

2023-12-05 13:21 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +6. Make sure that the Bundle ID is unique.
* “Bundle Identifier” would be more precise, as it is called in the UI.
* It'd be great to check the outcome, too: something like “...and the Signing Certificate is successfully assigned.”

I feel like we should be able to reference some Apple docs here, but I have no idea if they have anything concise and useful on the subject :)

2023-12-05 13:21 UTC, zamulla commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +you'll need to set the TEAM ID associated with your [Apple ID](https://support.apple.com/en-us/HT204316).
Let's make it “Team ID” here as well.

2023-12-05 13:21 UTC, zamulla commented on topics/multiplatform-publish-apps.md
> +If you need to configure other settings, use Xcode. After opening the project in Android Studio,
I was confused about whether these sentences were connected. Would a colon be beneficial here? “...use Xcode: after opening the project...” Something to link them together.

2023-12-05 17:31 UTC, danil-pavlov commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +6. Make sure that the Bundle ID is unique.
> I feel like we should be able to reference some Apple docs her
I agee, but I couldn't find anything that is specific for this case

2023-12-06 12:08 UTC, merged