Multiplatform onboarding fixes
JetBrains/kotlin-multiplatform-dev-docs pull request #37
Opened 2023-12-06 10:35 UTC by zamulla

Updated two main tutorials on Compose and KMP:
* https://www.jetbrains.com/help/kotlin-multiplatform-dev/multiplatform-getting-started.html
* https://www.jetbrains.com/help/kotlin-multiplatform-dev/compose-multiplatform-getting-started.html

2023-12-06 14:45 UTC, danil-pavlov commented on topics/compose-onboard/compose-multiplatform-create-first-app.md
> +2. Return to Android Studio.
2 and 3 could be 1 step:
> In Android Studio, select **iosApp** in the list of run configurations and click **Run**.

2023-12-06 14:54 UTC, danil-pavlov requested changes
Thank you for the huge work! A couple of small fixes plus please resolve the merge conflict

2023-12-06 16:21 UTC, zamulla commented on topics/multiplatfrom-onboard/multiplatform-create-first-app.md
> +If you want to run your application on another simulated device, you can add a new run configuration.
Yes, I re-read the section, you're right. But there is something to fix, I just didn't identify it properly in the text above: “if you don't have an available run configuration, add a new device.” Shouldn't it be “if you don't have an available run configuration, create one”? Following these steps, I'm not adding a new simulated device; that's a separate Xcode procedure.

And this sentence then makes sense as it is. The section title still bothers me, but not enough to dig in.

2023-12-07 17:08 UTC, danil-pavlov approved these changes

2023-12-08 07:12 UTC, merged