feat: new resource library
JetBrains/kotlin-multiplatform-dev-docs pull request #67
Opened 2024-02-06 14:25 UTC by danil-pavlov

2024-02-06 15:41 UTC, terrakok requested changes

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +               implementation("compose.components.resources")
`implementation(compose.components.resources)`

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +Store custom fonts in the `composeResources/font` directory as `*.ttf` files.
as `*.ttf` or `*.otf` files.

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +To load any file as a byte array, use the `Res.readBytes()` function:
use the `Res.readBytes(path)` function:

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +* The publication of Compose Multiplatform libraries with resources is not supported yet.
is not supported yet (in progress)

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +* Multimodule projects are not supported yet. Store all resources in the main application module.
is not supported yet (in progress)

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +* It's expected that resources are relatively small files, like icons and texts, that you load and use as part of the UI.
delete this sentence

2024-02-06 15:41 UTC, terrakok commented on topics/compose/compose-images-resources.md
> +
Add a new paragraph:
```
You my use special symbols in string resources:
 - '\n' - for a new line
 - '\t' - for a tab symbol
 - '\uXXXX' - for a custom unicode symbol
```

2024-02-07 15:43 UTC, terrakok approved these changes

2024-02-12 15:01 UTC, zamulla requested changes
Overall looks good, mostly phrasing nitpicks.

2024-02-13 12:50 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +You can use "light" or "dark" qualifiers. The resource is selected depending on the current system theme.
I think there's a confusion here. You can add different resources for the light and dark themes. If you don't, the default resource is chosen regardless of the system theme. But if you do, Compose chooses the appropriate resource automatically
Hope the new phrasing clarifies this

2024-02-13 12:52 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +There is no difference between `%...s` and `%...d `, for example:
No difference in implementation in composable code, updated the sentence

2024-02-13 12:53 UTC, danil-pavlov commented on topics/compose/compose-images-resources.md
> +You can place such files in the `composeResources/files` directory and create any hierarchy inside it.
I've edited the intro so it aligns with this part

2024-02-14 10:04 UTC, zamulla approved these changes
LGTM!

2024-02-14 17:10 UTC, merged