Whats new for Compose 1.6.0
JetBrains/kotlin-multiplatform-dev-docs pull request #77
Opened 2024-02-19 12:46 UTC by zamulla

2024-02-21 11:47 UTC, igordmn commented on topics/whats-new/whats-new-compose-1-6-0.md
> +* Jetpack Compose 1.6.1 was merged into Compose Multiplatform. Here is a [summary of changes](#jetpack-compose-1-6-1-merged-all-platforms)
We have found a link to the material3 1.2 as well: https://material.io/blog/material-3-compose-1-2.

It is worth to add it to the What's new. Maybe even describe the changes as we done that with main Compose.

2024-02-21 12:08 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +On iOS, the feature is available by default. To use the feature with Compose Multiplatform for Desktop, set the `compose.layers.type`
Please document a way how to switch to old behavior for the iOS (`latformLayers = false`) See https://github.com/JetBrains/compose-multiplatform-core/pull/1031 for details

2024-02-21 12:08 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +* `COMPONENT`, for creating `Popup` or `Dialog` as a separate Swing component in the same window. ??? It might work only with offscreen rendering.
Offscreen rendering (`compose.swing.render.on.graphics`) property is documented in 1.5.0 blogpost - https://blog.jetbrains.com/kotlin/2023/08/compose-multiplatform-1-5-0-release/#enhanced-swing-interop

Please note that `compose.swing.render.on.graphics` works only for `ComposePanel` but not for full window compose application

2024-02-21 12:08 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +        platformStyle = PlatformTextStyle(
We need to mention that this code is platform specific and NOT available in common sourceset

2024-02-21 12:08 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +### Add a way to use fonts installed on the system (Desktop, Web)
iOS works too

2024-02-21 12:09 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +If you set the `fontSize` attribute for a `Text` component in MaterialTheme but don't include `lineHeight`, actual line
Also, I'd mention that it's only about `material`, but not `material3`. `material3` had such behavior already

2024-02-26 10:56 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +> The feature will be supported on iOS in the next release. There are no plans for Android support.
It's been supported in iOS since 1.6.0-beta02

2024-02-26 10:56 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +(see [the code sample](https://github.com/JetBrains/compose-multiplatform-core/blob/jb-main/compose/desktop/desktop/samples/src/jvmMain/kotlin/androidx/compose/desktop/examples/fonts/Fonts.jvm.kt)
Please provide a link to a specific commit or at least to 1.6 branch - currently it points to `jb-main` that **will** be changed

2024-02-27 14:07 UTC, MatkovIvan commented on topics/whats-new/whats-new-compose-1-6-0.md
> +* The `includeFontPadding` parameter became `false` by default in Material 2.
```suggestion
* The `includeFontPadding` parameter became `false` on Android by default.
```
(it affects not only Material 2)

2024-02-27 18:02 UTC, danil-pavlov commented on mpd.tree
> +        <toc-element toc-title="Compose Multiplatform">
Since there's only one item,  I think we can remove this subheader for now

2024-02-27 19:24 UTC, danil-pavlov requested changes

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +You can use solid, double-width solid, dotted, dashed, and wavy line style. All available options can be found in
```suggestion
You can use solid, double-width solid, dotted, dashed, and wavy line styles. See all available options in
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +Example of the code that uses the `COMPONENT` property:
```suggestion
An example of the code that uses the `COMPONENT` property:
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +Example of setting a dotted underline style:
```suggestion
An example of setting a dotted underline style:
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +but needs to spawn an alert dialog. In 1.6.0 there is a way to reliably achieve that.
```suggestion
but needs to spawn an alert dialog. In 1.6.0, there is a way to achieve that reliably.
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +> rather than changing the font size directly. Alternatively, users can overwrite the line height like so:
```suggestion
> rather than change the font size directly. Alternatively, users can overwrite the line height like this:
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +>To support non-standard text sizes, we encourage users to follow the Material design system and use a different [type scale](https://m2.material.io/design/typography/the-type-system.html#type-scale)
```suggestion
> To support non-standard text sizes, we encourage users to follow the Material design system and use a different [type scale](https://m2.material.io/design/typography/the-type-system.html#type-scale)
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +
{type="tip"}

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +> `style = LocalTextStyle.current.copy(lineHeight = TextUnit.Unspecified)`, or create a custom `Typography` entirely.
```suggestion
> `style = LocalTextStyle.current.copy(lineHeight = TextUnit.Unspecified)` or create a custom `Typography` entirely.
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +If you set the `fontSize` attribute for a `Text` component in `MaterialTheme` but don't include `lineHeight`, actual line
```suggestion
If you set the `fontSize` attribute for a `Text` component in `MaterialTheme` but don't include `lineHeight`, the actual line
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +To use the feature with Compose Multiplatform for Desktop, set the `compose.layers.type`
```suggestion
To use the feature on desktop, set the `compose.layers.type`
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +With the added support for [LineHeightStyle.Trim](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineHeightStyle.Trim)
```suggestion
With the added support for [LineHeightStyle.Trim](https://developer.android.com/reference/kotlin/androidx/compose/ui/text/style/LineHeightStyle.Trim),
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +Jetpack Compose now [recommends](https://issuetracker.google.com/issues/321872412) not setting the font size directly:
We don't usually introduce notes. You can just include it in the note, like "Following Jetpack Compose recommendations, we also encourage users.."

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +### Padding for text with lineHeight set is trimmed by default
Just to keep headers consistent, currently, there is a mix of noun phrases and full sentences with verbs

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +in common Kotlin:
```suggestion
in common Kotlin more comfortably:
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +  components, not for full window Compose applications.
```suggestion
  components, not full window applications.
```

2024-02-27 19:24 UTC, danil-pavlov commented on topics/whats-new/whats-new-compose-1-6-0.md
> +  Downgrade the library to a version depending on Compose Multiplatform 1.5.12, or ask the library author to upgrade it
```suggestion
  Downgrade the library to a version depending on Compose Multiplatform 1.5.12 or ask the library author to upgrade it
```

2024-02-28 12:28 UTC, koshachy approved these changes

2024-02-28 12:29 UTC, danil-pavlov approved these changes

2024-02-28 12:31 UTC, merged