feat: compose desktop components
JetBrains/kotlin-multiplatform-dev-docs pull request #80
Opened 2024-02-20 15:41 UTC by danil-pavlov

2024-02-26 17:13 UTC, zamulla requested changes
LGTM overall, I left some low-level suggestions.

2024-02-26 17:13 UTC, zamulla commented on topics/compose/compose-desktop-components.md
> +You can install mouse event listeners on the components in your desktop project. These could be click, move, enter, and
I think one can add, register, or set up event listeners; but in any case "install" feels too weighty here.

The second sentence could be clearer with rephrasing like: "You can listen for clicks, cursor movement, cursor entering an area (?) and scrolling."

2024-02-26 17:13 UTC, zamulla commented on topics/compose/compose-desktop-components.md
> +By default, the tabbed navigation moves between focusable components in the order of their appearance. Focusable
```suggestion
By default, the tabbed navigation moves focus between focusable components in the order of their appearance. Focusable
```

Or "allows moving"; the navigation itself shouldn't move :)

2024-02-27 16:01 UTC, danil-pavlov commented on topics/compose/compose-desktop-components.md
> +        painter = painterResource("sample.png"),
We should update this sample, I agree, but the main idea of this page was to give a short overview and promote full tutorials. I'll contact the team so that they update it

2024-02-27 16:03 UTC, danil-pavlov commented on topics/compose/compose-desktop-components.md
> +{initial-collapse-state="collapsed"}
Great idea with the titles. Unfortunately, it's impossible to use the lines that have quotation marks, it breaks the markup. So I included different ones

2024-02-28 08:21 UTC, koshachy approved these changes
Nice overview!
Some nitpicks though, but everything is up to you.

2024-02-28 08:21 UTC, koshachy commented on topics/compose/compose-desktop-components.md
> +Default context menu options are copy, cut, paste, and select all. You can add more menu items, customize style and
IDK, but for me easier to read "Default context menu options include copy, cut, past, and select all."

2024-02-28 11:40 UTC, danil-pavlov commented on topics/compose/compose-desktop-components.md
> +[//]: # (title: Desktop-specific components and events)
We also now have  iOS-specific section, so maybe we should rename Android instead

2024-02-29 13:29 UTC, zamulla approved these changes
LGTM!

2024-03-01 15:34 UTC, merged