fix: several clarifications to make the path smoother
JetBrains/kotlin-multiplatform-dev-docs pull request #85
Opened 2024-03-04 11:48 UTC by zamulla

The tutorial was reported as outdated, but nothing much has changed to prevent it from working. However, several clarity issues can make the impression of code that's not working.

2024-03-04 11:56 UTC, koshachy requested changes
Some comments.

UPD: Sorry, haven't noticed that it is just a draft!

2024-03-04 11:56 UTC, koshachy commented on topics/multiplatform-run-tests.md
> +   Create a new directory in the `shared/src` folder.
folder vs directory :)
If you refer to a project structure, use "directory".

2024-03-04 11:56 UTC, koshachy commented on topics/multiplatform-run-tests.md
> +   package common.example.search
It seems that something is wrong with the indentation of the code 🤔

2024-03-04 11:56 UTC, koshachy commented on topics/multiplatform-run-tests.md
> +   Create a new directory in the `shared/src` folder.
If you refer to a regular OS file system, use "folder"

2024-03-05 12:29 UTC, zamulla commented on topics/multiplatform-run-tests.md
> +   Create a new directory in the `shared/src` folder.
Done with folders, tell me if it looks consistent to you.

2024-03-05 15:38 UTC, koshachy commented on topics/multiplatform-run-tests.md
> +3. In the `commonTest/kotlin` folder, create a new `org.kmp.testing` package.
In line 90, there is "directory"
In line 191, there is  "folder"
But they look pretty same 🤔

2024-03-05 15:38 UTC, koshachy approved these changes
One minor comment.

2024-03-06 11:08 UTC, merged